/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */


#import "xenia/ui/ios/launcher/ios_compat_formatting.h"

#include <iterator>

// Autogenerated by `xb premake`.
#include "build/version.h"

#ifndef XE_BUILD_VERSION
#define XE_BUILD_VERSION "1.0.0"
#endif

#ifndef XE_BUILD_NUMBER
#define XE_BUILD_NUMBER "0"
#endif

#ifndef XE_BUILD_COMMIT_SHORT
#define XE_BUILD_COMMIT_SHORT ""
#endif

#import "xenia/ui/ios/shared/ios_theme.h"
#import "xenia/ui/ios/shared/ios_view_helpers.h"

namespace {

// Compatibility taxonomy: status / perf / channel / release-stage all share
// the same "code → label / color / rank" lookup shape, so a single struct +
// generic FindByCode() drive every accessor below. `hex_color == 0` means
// render with [XeniaTheme textMuted]; `rank` is only meaningful for
// statuses (higher = "more playable").
struct CompatTaxonomyEntry {
  NSString* code;
  NSString* label;
  uint32_t hex_color;
  NSInteger rank;
};

const CompatTaxonomyEntry kCompatStatuses[] = {
    {@"playable", @"Playable", 0x34d399, 4}, {@"ingame", @"In-Game", 0x60a5fa, 3},
    {@"intro", @"Intro", 0xfbbf24, 2},       {@"loads", @"Loads", 0xfb923c, 1},
    {@"nothing", @"Nothing", 0xf87171, 0},
};

const CompatTaxonomyEntry kCompatStatusUntested = {@"untested", @"Untested", 0, 0};

const CompatTaxonomyEntry kCompatPerfs[] = {
    {@"great", @"Great", 0x34d399, 0},
    {@"ok", @"Okay", 0x60a5fa, 0},
    {@"poor", @"Poor", 0xfbbf24, 0},
    {@"n/a", @"N/A", 0, 0},
};

UIColor* ColorFromTaxonomy(const CompatTaxonomyEntry& entry) {
  return entry.hex_color ? XEColorFromHexRGB(entry.hex_color) : [XeniaTheme textMuted];
}

const CompatTaxonomyEntry* FindByCode(const CompatTaxonomyEntry* entries, size_t count,
                                      NSString* code) {
  for (size_t i = 0; i < count; ++i) {
    if ([entries[i].code isEqualToString:code]) {
      return &entries[i];
    }
  }
  return nullptr;
}

const CompatTaxonomyEntry* FindCompatStatus(NSString* code) {
  if (const CompatTaxonomyEntry* entry =
          FindByCode(kCompatStatuses, std::size(kCompatStatuses), code)) {
    return entry;
  }
  if ([code isEqualToString:kCompatStatusUntested.code]) {
    return &kCompatStatusUntested;
  }
  return nullptr;
}

const CompatTaxonomyEntry* FindCompatPerf(NSString* code) {
  return FindByCode(kCompatPerfs, std::size(kCompatPerfs), code);
}

}  // namespace

UIColor* xe_compat_status_color(NSString* status) {
  const CompatTaxonomyEntry* entry = FindCompatStatus(status);
  return entry ? ColorFromTaxonomy(*entry) : [XeniaTheme textMuted];
}

NSString* xe_compat_status_label(NSString* status) {
  const CompatTaxonomyEntry* entry = FindCompatStatus(status);
  return entry ? entry->label : @"Unknown";
}

UIColor* xe_compat_perf_color(NSString* perf) {
  const CompatTaxonomyEntry* entry = FindCompatPerf(perf);
  return entry ? ColorFromTaxonomy(*entry) : [XeniaTheme textMuted];
}

NSString* xe_compat_perf_label(NSString* perf) {
  const CompatTaxonomyEntry* entry = FindCompatPerf(perf);
  return entry ? entry->label : @"Unknown";
}

NSString* xe_format_iso_date(NSString* iso) {
  if (!iso || iso.length < 10) {
    return iso ?: @"";
  }
  static NSDateFormatter* parser = nil;
  static NSDateFormatter* date_only_parser = nil;
  static NSDateFormatter* formatter = nil;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    parser = [[NSDateFormatter alloc] init];
    parser.dateFormat = @"yyyy-MM-dd'T'HH:mm:ss";
    parser.locale = [[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease];
    date_only_parser = [[NSDateFormatter alloc] init];
    date_only_parser.dateFormat = @"yyyy-MM-dd";
    date_only_parser.locale =
        [[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"] autorelease];
    formatter = [[NSDateFormatter alloc] init];
    formatter.dateStyle = NSDateFormatterMediumStyle;
    formatter.timeStyle = NSDateFormatterNoStyle;
  });

  NSString* trimmed = [iso substringToIndex:MIN(iso.length, (NSUInteger)19)];
  NSDate* date = [parser dateFromString:trimmed];
  if (!date) {
    date = [date_only_parser dateFromString:[iso substringToIndex:MIN(iso.length, (NSUInteger)10)]];
  }
  return date ? [formatter stringFromDate:date]
              : [iso substringToIndex:MIN(iso.length, (NSUInteger)10)];
}

NSString* xe_platform_display_text(NSString* platform, NSString* os_version) {
  if (![platform isKindOfClass:[NSString class]] || platform.length == 0) {
    return @"";
  }
  NSString* platform_name = [platform isEqualToString:@"ios"]     ? @"iOS"
                            : [platform isEqualToString:@"macos"] ? @"macOS"
                                                                  : platform;
  if (![os_version isKindOfClass:[NSString class]] || os_version.length == 0) {
    return platform_name;
  }
  return [NSString stringWithFormat:@"%@ %@", platform_name, os_version];
}

NSString* xe_string_from_object(id value) {
  return [value isKindOfClass:[NSString class]] ? (NSString*)value : nil;
}

NSDictionary* xe_dictionary_from_object(id value) {
  return [value isKindOfClass:[NSDictionary class]] ? (NSDictionary*)value : nil;
}

NSInteger xe_compat_status_rank(NSString* status) {
  const CompatTaxonomyEntry* entry = FindCompatStatus(status);
  return entry ? entry->rank : 0;
}

namespace {

const CompatTaxonomyEntry kCompatChannels[] = {
    {@"release", @"Release", 0x34d399, 0},
    {@"preview", @"Preview", 0x60a5fa, 0},
    {@"self-built", @"Self-Built", 0, 0},
};

const CompatTaxonomyEntry kReleaseStages[] = {
    {@"alpha", @"Alpha", 0, 0},
    {@"beta", @"Beta", 0, 0},
    {@"rc", @"RC", 0, 0},
};

}  // namespace

UIColor* xe_compat_channel_color(NSString* channel) {
  const CompatTaxonomyEntry* entry =
      FindByCode(kCompatChannels, std::size(kCompatChannels), channel);
  if (entry && entry->hex_color) {
    return ColorFromTaxonomy(*entry);
  }
  return [XeniaTheme textMuted];
}

NSString* xe_compat_channel_label(NSString* channel) {
  const CompatTaxonomyEntry* entry =
      FindByCode(kCompatChannels, std::size(kCompatChannels), channel);
  return entry ? entry->label : @"Unknown";
}

static NSString* xe_release_stage_display_label(NSString* stage) {
  const CompatTaxonomyEntry* entry = FindByCode(kReleaseStages, std::size(kReleaseStages), stage);
  return entry ? entry->label : nil;
}

static NSString* xe_build_version_label(NSDictionary* build_info) {
  NSString* app_version = xe_string_from_object(build_info[@"appVersion"]);
  NSString* build_number = xe_string_from_object(build_info[@"buildNumber"]);
  if (app_version.length > 0 && build_number.length > 0) {
    return [NSString stringWithFormat:@"%@-%@", app_version, build_number];
  }
  if (app_version.length > 0) {
    return app_version;
  }
  return nil;
}

NSString* xe_compat_build_label(NSDictionary* build_info) {
  NSString* channel = xe_string_from_object(build_info[@"channel"]);
  NSString* commit_short = xe_string_from_object(build_info[@"commitShort"]);
  if ([channel isEqualToString:@"self-built"] && commit_short.length > 0) {
    return commit_short;
  }

  NSString* version_label = xe_build_version_label(build_info);
  if (version_label.length > 0) {
    return version_label;
  }
  NSString* build_number = xe_string_from_object(build_info[@"buildNumber"]);
  if (build_number.length > 0) {
    return [NSString stringWithFormat:@"Build %@", build_number];
  }
  NSString* build_id = xe_string_from_object(build_info[@"buildId"]);
  return build_id.length > 0 ? build_id : nil;
}

NSString* xe_user_facing_build_label(NSDictionary* build_info) {
  if (!build_info) {
    return @"Unknown Build";
  }

  NSString* channel = xe_string_from_object(build_info[@"channel"]);
  NSString* stage_label =
      xe_release_stage_display_label(xe_string_from_object(build_info[@"stage"]));
  NSString* version_label = xe_build_version_label(build_info);
  NSString* commit_short = xe_string_from_object(build_info[@"commitShort"]);

  if ([channel isEqualToString:@"preview"] && version_label.length > 0) {
    if (stage_label.length > 0) {
      return [NSString stringWithFormat:@"%@ Preview %@", stage_label, version_label];
    }
    return [NSString stringWithFormat:@"Preview %@", version_label];
  }
  if ([channel isEqualToString:@"release"] && version_label.length > 0) {
    if (stage_label.length > 0) {
      return [NSString stringWithFormat:@"%@ %@", stage_label, version_label];
    }
    return version_label;
  }
  if (commit_short.length > 0) {
    return [NSString stringWithFormat:@"Dev build %@", commit_short];
  }
  if (version_label.length > 0) {
    return [NSString stringWithFormat:@"Build %@", version_label];
  }

  NSString* build_number = xe_string_from_object(build_info[@"buildNumber"]);
  if (build_number.length > 0) {
    return [NSString stringWithFormat:@"Build %@", build_number];
  }

  NSString* build_id = xe_string_from_object(build_info[@"buildId"]);
  return build_id.length > 0 ? [NSString stringWithFormat:@"Build %@", build_id] : @"Unknown Build";
}

static NSString* xe_sanitize_build_component(NSString* value) {
  if (![value isKindOfClass:[NSString class]] || value.length == 0) {
    return @"unknown";
  }
  NSMutableString* sanitized = [NSMutableString stringWithCapacity:value.length];
  NSCharacterSet* alnum = [NSCharacterSet alphanumericCharacterSet];
  BOOL last_was_dash = NO;
  NSString* lower = [value lowercaseString];
  for (NSUInteger i = 0; i < lower.length; ++i) {
    unichar c = [lower characterAtIndex:i];
    if ([alnum characterIsMember:c]) {
      [sanitized appendFormat:@"%C", c];
      last_was_dash = NO;
    } else if (!last_was_dash) {
      [sanitized appendString:@"-"];
      last_was_dash = YES;
    }
  }
  while ([sanitized hasPrefix:@"-"]) {
    [sanitized deleteCharactersInRange:NSMakeRange(0, 1)];
  }
  while ([sanitized hasSuffix:@"-"]) {
    [sanitized deleteCharactersInRange:NSMakeRange(sanitized.length - 1, 1)];
  }
  return sanitized.length > 0 ? sanitized : @"unknown";
}

static NSString* xe_make_build_id(NSString* platform, NSString* channel, NSString* app_version,
                                  NSString* build_number, NSString* stage) {
  NSString* base = [NSString stringWithFormat:@"%@-%@-%@-%@", xe_sanitize_build_component(platform),
                                              xe_sanitize_build_component(channel),
                                              xe_sanitize_build_component(app_version),
                                              xe_sanitize_build_component(build_number)];
  if ([stage isKindOfClass:[NSString class]] && stage.length > 0 &&
      ![stage isEqualToString:@"stable"]) {
    return [base stringByAppendingFormat:@"-%@", xe_sanitize_build_component(stage)];
  }
  return base;
}

NSDictionary* xe_compat_build_info_from_entry(NSDictionary* entry) {
  if (!entry) {
    return nil;
  }
  NSDictionary* nested = xe_dictionary_from_object(entry[@"build"]);
  NSString* build_id = xe_string_from_object(nested ? nested[@"buildId"] : entry[@"buildId"]);
  NSString* channel = xe_string_from_object(nested ? nested[@"channel"] : entry[@"channel"]);
  id official_value = nested ? nested[@"official"] : entry[@"official"];
  NSNumber* official =
      [official_value isKindOfClass:[NSNumber class]] ? (NSNumber*)official_value : nil;
  NSString* app_version =
      xe_string_from_object(nested ? nested[@"appVersion"] : entry[@"appVersion"]);
  NSString* build_number =
      xe_string_from_object(nested ? nested[@"buildNumber"] : entry[@"buildNumber"]);
  NSString* commit_short =
      xe_string_from_object(nested ? nested[@"commitShort"] : entry[@"commitShort"]);
  NSString* stage = xe_string_from_object(nested ? nested[@"stage"] : entry[@"stage"]);
  if (build_id.length == 0 && channel.length == 0 && app_version.length == 0 &&
      build_number.length == 0 && commit_short.length == 0 && stage.length == 0 && !official) {
    return nil;
  }

  NSMutableDictionary* build = [NSMutableDictionary dictionary];
  if (build_id.length > 0) {
    build[@"buildId"] = build_id;
  }
  if (channel.length > 0) {
    build[@"channel"] = channel;
  }
  if (official) {
    build[@"official"] = official;
  }
  if (app_version.length > 0) {
    build[@"appVersion"] = app_version;
  }
  if (build_number.length > 0) {
    build[@"buildNumber"] = build_number;
  }
  if (commit_short.length > 0) {
    build[@"commitShort"] = commit_short;
  }
  if (stage.length > 0) {
    build[@"stage"] = stage;
  }
  return build.count > 0 ? build : nil;
}

NSDictionary* xe_current_compat_report_build_info(void) {
  static NSDictionary* build_info = nil;
  static dispatch_once_t once_token;
  dispatch_once(&once_token, ^{
    NSBundle* bundle = [NSBundle mainBundle];
    NSString* app_version =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"CFBundleShortVersionString"]);
    NSString* build_number =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"CFBundleVersion"]);
    NSString* compiled_app_version = [NSString stringWithUTF8String:XE_BUILD_VERSION];
    NSString* compiled_build_number = [NSString stringWithUTF8String:XE_BUILD_NUMBER];
    BOOL uses_placeholder_bundle_version =
        (app_version.length == 0 || [app_version isEqualToString:@"1.0"]) &&
        (build_number.length == 0 || [build_number isEqualToString:@"1"]);
    if (uses_placeholder_bundle_version) {
      app_version = compiled_app_version.length > 0 ? compiled_app_version : @"1.0.0";
      build_number = compiled_build_number.length > 0 ? compiled_build_number : @"0";
    } else {
      if (app_version.length == 0) {
        app_version = compiled_app_version.length > 0 ? compiled_app_version : @"1.0.0";
      }
      if (build_number.length == 0) {
        build_number = compiled_build_number.length > 0 ? compiled_build_number : @"0";
      }
    }

    NSString* attested_channel =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"XeniOSBuildChannel"]);
    NSString* build_stage =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"XeniOSBuildStage"]);
    NSString* attestation_payload =
        xe_string_from_object([bundle objectForInfoDictionaryKey:@"XeniOSBuildAttestationPayload"]);
    NSString* attestation_signature = xe_string_from_object(
        [bundle objectForInfoDictionaryKey:@"XeniOSBuildAttestationSignature"]);
    BOOL has_attested_channel = [attested_channel isEqualToString:@"release"] ||
                                [attested_channel isEqualToString:@"preview"];
    BOOL has_attestation = attestation_payload.length > 0 && attestation_signature.length > 0;
    NSString* channel = has_attested_channel && has_attestation ? attested_channel : @"self-built";
    BOOL official = has_attested_channel && has_attestation;
    NSString* commit_short = [NSString stringWithUTF8String:XE_BUILD_COMMIT_SHORT];
    NSString* build_id = xe_make_build_id(@"ios", channel, app_version, build_number, build_stage);

    NSMutableDictionary* mutable_build_info = [NSMutableDictionary
        dictionaryWithObjectsAndKeys:build_id, @"buildId", channel, @"channel", @(official),
                                     @"official", app_version, @"appVersion", build_number,
                                     @"buildNumber", commit_short, @"commitShort", nil];
    if (build_stage.length > 0) {
      mutable_build_info[@"stage"] = build_stage;
    }
    if (has_attestation) {
      mutable_build_info[@"attestation"] = @{
        @"payload" : attestation_payload,
        @"signature" : attestation_signature,
      };
    }
    build_info = [mutable_build_info copy];
  });
  return build_info;
}

NSArray<NSString*>* xe_compat_statuses(void) {
  NSMutableArray<NSString*>* codes = [NSMutableArray arrayWithCapacity:std::size(kCompatStatuses)];
  for (const auto& entry : kCompatStatuses) {
    [codes addObject:entry.code];
  }
  return codes;
}

NSArray<NSString*>* xe_compat_status_labels(void) {
  NSMutableArray<NSString*>* labels = [NSMutableArray arrayWithCapacity:std::size(kCompatStatuses)];
  for (const auto& entry : kCompatStatuses) {
    [labels addObject:entry.label];
  }
  return labels;
}

NSArray<NSString*>* xe_compat_perfs(void) {
  NSMutableArray<NSString*>* codes = [NSMutableArray arrayWithCapacity:std::size(kCompatPerfs)];
  for (const auto& entry : kCompatPerfs) {
    [codes addObject:entry.code];
  }
  return codes;
}

// Picker labels keep "OK" (vs. xe_compat_perf_label's "Okay") so the report
// submission buttons show the short form the website also uses.
NSArray<NSString*>* xe_compat_perf_labels(void) { return @[ @"Great", @"OK", @"Poor", @"N/A" ]; }

CGFloat xe_compat_hero_height_for_width(CGFloat width, UIImage* background_art) {
  CGFloat hero_width = MAX(width, 0.0);
  if (hero_width <= 0.0) {
    return 286.0;
  }
  // When background art is available, derive height from the image aspect
  // ratio so the hero card shows more of the artwork.
  if (background_art && background_art.size.width > 0.0 && background_art.size.height > 0.0) {
    CGFloat image_aspect = background_art.size.width / background_art.size.height;
    CGFloat derived = floor(hero_width / image_aspect);
    return MIN(360.0, MAX(240.0, derived));
  }
  return MIN(360.0, MAX(286.0, floor(hero_width * 0.74)));
}
